conn_lc:although conn:Although conn_POS:IN xxx£
conn_lc:also conn:also conn_POS:RB with_prev_full:employee_also xxx£
conn_lc:until conn:until conn_POS:IN with_prev_full:action_until xxx£
conn_lc:also conn:also conn_POS:RB with_prev_full:keeth_also xxx£
conn_lc:after conn:after conn_POS:IN with_prev_full:defense_after xxx£
conn_lc:but conn:but conn_POS:CC with_prev_full:,_but xxx£
conn_lc:although conn:Although conn_POS:IN xxx£
