conn_lc:later conn:Later conn_POS:RB xxx£
conn_lc:then conn:then conn_POS:RB with_prev_full:and_then xxx£
conn_lc:but conn:But conn_POS:CC xxx£
conn_lc:but conn:But conn_POS:CC xxx£
conn_lc:and conn:And conn_POS:CC xxx£
conn_lc:when conn:When conn_POS:WRB with_prev_full:``_when xxx£
conn_lc:so conn:so conn_POS:IN with_prev_full:humans_so xxx£
conn_lc:and conn:and conn_POS:CC with_prev_full:,_and xxx£
conn_lc:because conn:because conn_POS:IN with_prev_full:that_because xxx£
