conn_lc:when conn:when conn_POS:WRB with_prev_full:mark_when xxx£
conn_lc:if conn:if conn_POS:IN with_prev_full:enacted_if xxx£
conn_lc:for_example conn:for_example conn_POS:IN_NN with_prev_full:,_for_example xxx£
conn_lc:after conn:after conn_POS:IN with_prev_full:right_after xxx£
conn_lc:if conn:if conn_POS:IN with_prev_full:,_if xxx£
conn_lc:also conn:also conn_POS:RB with_prev_full:are_also xxx£
conn_lc:if conn:If conn_POS:IN xxx£
