conn_lc:moreover conn:Moreover conn_POS:RB xxx£
conn_lc:if conn:if conn_POS:IN with_prev_full:company_if xxx£
conn_lc:also conn:also conn_POS:RB with_prev_full:mg_also xxx£
conn_lc:also conn:also conn_POS:RB with_prev_full:suit_also xxx£
conn_lc:but conn:But conn_POS:CC xxx£
conn_lc:also conn:also conn_POS:RB with_prev_full:company_also xxx£
conn_lc:when conn:when conn_POS:WRB with_prev_full:only_when xxx£
conn_lc:and conn:and conn_POS:CC with_prev_full:1993_and xxx£
conn_lc:if conn:if conn_POS:IN with_prev_full:avoided_if xxx£
