conn_lc:in_particular conn:In_particular conn_POS:IN_JJ xxx£
conn_lc:also conn:also conn_POS:RB with_prev_full:congress_also xxx£
conn_lc:as conn:as conn_POS:IN with_prev_full:,_as xxx£
conn_lc:also conn:also conn_POS:RB with_prev_full:conference_also xxx£
conn_lc:once conn:once conn_POS:IN with_prev_full:accelerate_once xxx£
conn_lc:also conn:also conn_POS:RB with_prev_full:group_also xxx£
conn_lc:and conn:and conn_POS:CC with_prev_full:,_and xxx£
