conn_lc:when conn:when conn_POS:WRB with_prev_full:occurred_when xxx£
conn_lc:and conn:and conn_POS:CC with_prev_full:,_and xxx£
conn_lc:if conn:if conn_POS:IN with_prev_full:workers_if xxx£
conn_lc:however conn:however conn_POS:RB with_prev_full:,_however xxx£
conn_lc:if conn:if conn_POS:IN with_prev_full:group_if xxx£
conn_lc:if conn:if conn_POS:IN with_prev_full:troops_if xxx£
conn_lc:after conn:after conn_POS:IN with_prev_full:infighting_after xxx£
conn_lc:but conn:but conn_POS:CC with_prev_full:,_but xxx£
