conn_lc:and conn:and conn_POS:CC with_prev_full:producer_and xxx£
conn_lc:meanwhile conn:Meanwhile conn_POS:RB xxx£
conn_lc:then conn:then conn_POS:RB with_prev_full:,_then xxx£
conn_lc:but conn:but conn_POS:CC with_prev_full:,_but xxx£
conn_lc:although conn:Although conn_POS:IN xxx£
conn_lc:in_the_end conn:in_the_end conn_POS:IN_DT_NN with_prev_full:``_in_the_end xxx£
conn_lc:because conn:Because conn_POS:IN with_prev_full:u.s._because xxx£
